[build]
builder = "nixpacks"
buildCommand = "npm install --prefix client && CI=false npm run build --prefix client && npm install --prefix server"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
